# Generated by Django 5.1.6 on 2025-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Testimonial',
            new_name='testimonial',
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
